### ISSUE TITLE
Load Scan

### ISSUE THREAD

**Issue by babssmm** [issamdakir/BDENTAL#4]
Thanks for the great Add-ons 
I am trying to load a dicom series into bdental scan viewer, set project folder, Dicom series, and Dicom series folder and get this error: 
"
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BDENTAL-main\Operators\BDENTAL_ScanOperators.py", line 653, in execute
    DcmInfo = Load_Dicom_funtion(context, self.q)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BDENTAL-main\Operators\BDENTAL_ScanOperators.py", line 145, in Load_Dicom_funtion
    MaxSerie, MaxCount = GetMaxSerie(UserDcmDir)
ValueError: not enough values to unpack (expected 2, got 1)

location: <unknown location>:-1
"

Could you please help solving? 
Many thanks

**Comment by issamdakir** [comment]
hi are you dentist,
just give me some days i ll upload a new version of the addon and send you
link.
ps : this version you downloaded  is old and deprecated no more maintained

**Comment by babssmm** [comment]
Hi thanks so much for the reply.
Really appreciate.
Kind regards
Bruno


A terça, 1/02/2022, 13:42, Dr issam Dakir ***@***.***>
escreveu:

> hi are you dentist,
> just give me some days i ll upload a new version of the addon and send you
> link.
> ps : this version you downloaded is old and deprecated no more maintained
>
